### ISSUE TITLE
PreTrain model

### ISSUE THREAD

**Issue by 5Yesterday** [wangguanan/HOReID#13]
How to train the pretrain model?

**Comment by wangguanan** [comment]
as shown in readme.md

the experimental results can be easily got by running the training command 

```
python main.py --mode train \
--duke_path path/to/occluded/duke \
--output_path ./results 
```

before that, the dataset should be downloaded from [here](https://github.com/lightas/Occluded-DukeMTMC-Dataset)

**Comment by 5Yesterday** [comment]
I mean it: 
Pre-trained Pose Model (pose_hrnet_w48_256x192.pth, please download it to path ./core/models/model_keypoints/pose_hrnet_w48_256x192.pth

**Comment by wangguanan** [comment]
please refer to 
https://github.com/microsoft/human-pose-estimation.pytorch
