### ISSUE TITLE
Details about experiments on occluded datasets and partial datasets

### ISSUE THREAD

**Issue by dcp15** [wangguanan/HOReID#15]
Thanks for opening the code!  I want to figure out the training dataset of Occluded-REID.  Is it Occluded-Duke? or other ones?
Besides, for Partial-REID and Partial-iLIDS, the training dataset is market, whether fine-tuning is performed on them?

**Comment by chenxiangzZ** [comment]
you can refer to the cloded issues, the auther answered it,

**Comment by wangguanan** [comment]
> you can refer to the cloded issues, the auther answered it,

Thanks for your reply.

The training dataset for occluded-reid, partial-ilids, partial-reid are market. 
thanks.
