### ISSUE TITLE
can you share the Occulded Reid datasets link?

### ISSUE THREAD

**Issue by Yx1322441675** [wangguanan/HOReID#18]
i can't find the link of the Occulded Reid datasets link?can you share it ?

**Comment by wangguanan** [comment]
please find it on baidu disk

链接: https://pan.baidu.com/s/1eTahCQW6xjX92kjfmlkOiA  密码: o1cr


we will release a strong baseline for occluded-reid, parital-reid and partial-ilids, 
please keep paying attention to my github.
