### ISSUE TITLE
how do you organize the dataset for training？

### ISSUE THREAD

**Issue by Kewenjing1020** [wangguanan/HOReID#2]
Hi Guanan, I read your paper and have some questions about the experiment, especially on datasets. Here I list my questions:
1. Since the occluded datasets are small, have you pre-trained your model on any holistic datasets?
2. For the experiments on occluded-duke, how do you sample the images? In each batch, the number of occluded images is fixed or not? Will you repeat the occluded images since they much less than whole-body images? 
3. The occluded-REID don't have a training set, the model evaluated on occluded-REID is trained on which datasets?

**Comment by wangguanan** [comment]
Hi, Thanks for your attention.
For all partial/occluded datasets except for occluded-duke, we trained our model on market-1501 dataset, and evaluate the model on partial/occluded datasets separately.
For Occluded-Duke, we follow  FPGA [26] that train the model on DukeMTMC-reID and evaluate on Occluded-Duke.
