### ISSUE TITLE
关于partial dataset以及occluded-ReID数据集的测试代码

### ISSUE THREAD

**Issue by victor-gui** [wangguanan/HOReID#21]
您好,感谢您这篇文章所做的工作,我在跑您的代码时碰到了一些问题:
当我直接在Market-1501上训练,然后在Occluded-REID以及Partial-REID数据集上测试时,并没有得到您论文中所展示的结果,请问在测试的时候有什么要注意的吗?或者您是否能给我发一份这几个数据集的测试代码,我的邮箱:2574130682@qq.com,非常感谢!

**Comment by wangguanan** [comment]
please refer to https://github.com/wangguanan/HOReID/issues/22
thanks.
