### ISSUE TITLE
How can i train on the datasets Occluded-reid,partial-reid,Market-1501 in your paper?

### ISSUE THREAD

**Issue by Yx1322441675** [wangguanan/HOReID#22]
How can i train on the datasets Occluded-reid,partial-reid,Market-1501 in your paper?
can you share the dataset and details ?
thank you

**Comment by wangguanan** [comment]
we provide our baseline model (cnn+skeleton, without gcn and gm parts) [here](https://github.com/wangguanan/light-reid/tree/master/examples/occluded_reid)
it also achieves very high accuracy outperforming most state-of-the-art models.
