### ISSUE TITLE
how to test on partial REID

### ISSUE THREAD

**Issue by Mrkkew** [wangguanan/HOReID#4]
Hello! I want to ask how to train on Market and test on partial REID and partial iLIDS dataset?
what's more, I couldn't find the whole partial iLIDS dataset which containing 238 images.Can you share a link about dataset?
looking forward to your reply.

**Comment by Mrkkew** [comment]
hello,can you answer my question? I don't know how to train on Market and test on partial REID and partial iLIDS dataset.

**Comment by wangguanan** [comment]
Thanks for your attention, dataset has been sent to your e-mail.
