### ISSUE TITLE
Color jitter augmentation

### ISSUE THREAD

**Issue by kimx3966** [wangguanan/HOReID#5]
In the paper, you said "When test on occluded/partial datasets, we use **extra color jitter augmentation** to avoid domain variance." But, when I looked at your code, I was not able to find that augmentation part. Can you let me know how you did it? for example, some setting for **torchvision.transforms.ColorJitter**. I'd appreciate some help. Thanks in advance.

**Comment by wangguanan** [comment]
sorry for the late response. the setting is as below:

```
'colorjitor': transforms.ColorJitter(brightness=0.25, contrast=0.15, saturation=0.25, hue=0),
```
