### ISSUE TITLE
inference代码

### ISSUE THREAD

**Issue by woshizhangcheng** [wangguanan/HOReID#6]
你好，不知能否分享inference文件

**Comment by wangguanan** [comment]
你好，训练和测试都在这个代码仓里，你直接运行就可以得到训练和测试的结果，

**Comment by woshizhangcheng** [comment]
> 你好，训练和测试都在这个代码仓里，你直接运行就可以得到训练和测试的结果，

谢谢，跑出了结果
base+gcn, Dataset: Duke  
mAP: 0.45936994972097783 
Rank: [0.57330317 0.64434389 0.67963801 ... 1.         1.         1.        ]

当我尝试接入视频提取特征，需要一张一张提取人体特征，故修改了加载数据的batchsize，运行到这里会出错
```
bned_feature_vector_list, cls_score_list = self.bnclassifiers(feature_vector_list)
提示：ValueError: expected 2D or 3D input (got 1D input)
```
修改了数据输入的batchsize
```
默认：
self.duke_query_loader = self._get_loader(self.duke_query_samples, self.transform_test, 128)
self.duke_gallery_loader = self._get_loader(self.duke_gallery_samples, self.transform_test, 128)
-----------------------------------
修改后：
self.duke_query_loader = self._get_loader(self.duke_query_samples, self.transform_test, 1)
self.duke_gallery_loader = self._get_loader(self.duke_gallery_samples, self.transform_test, 1)
```
forward的时候如果batchsize=1会报维度错误，我该如何修改，谢谢
![Snipaste_2020-07-28_15-26-43](https://user-images.githubusercontent.com/34908468/88632866-c8e92700-d0e6-11ea-99fc-174a4571fd41.jpg)

**Comment by chgit0214** [comment]
我遇到了同样的问题，请问解决了吗 @nobody-cheng

**Comment by chenxiangzZ** [comment]
@nobody-cheng @chenhaoCSDN 
你好，请问你们在market数据集上怎么训练呢？而且在duck上的结果我也不是很准确！

**Comment by wangguanan** [comment]
你好，目前不支持batchsize=1， 只要bs>2应该就不会报错。
后面会修复这个bug的，谢谢。

**Comment by wangguanan** [comment]
> @nobody-cheng @chenhaoCSDN
> 你好，请问你们在market数据集上怎么训练呢？而且在duck上的结果我也不是很准确！

 你好，在occluded-Duke数据库上的点应该是准确的，且比论文中的点还高一些。如果结果差距很大，可能是您运行方式有错误，可以把问题反馈上来。

maket的训练代码暂时还没有整理，抱歉。

**Comment by chenxiangzZ** [comment]
@wangguanan 
感谢解答！是的，在occluded-Duke上的结果是会高些，我发现在duck-mtmc下的结果，反而base下的结果比base+gcn+gm还要高，请问为啥呢

**Comment by wangguanan** [comment]
> @wangguanan
> 感谢解答！是的，在occluded-Duke上的结果是会高些，我发现在duck-mtmc下的结果，反而base下的结果比base+gcn+gm还要高，请问为啥呢

duke、market 的训练参数和 occluded-duke 不一样。
另外因为 duke 中 遮挡 case 很少（相比 occluded duke），因此长点不明显。

**Comment by chenxiangzZ** [comment]
> > @wangguanan
> > 感谢解答！是的，在occluded-Duke上的结果是会高些，我发现在duck-mtmc下的结果，反而base下的结果比base+gcn+gm还要高，请问为啥呢
> 
> duke、market 的训练参数和 occluded-duke 不一样。
> 另外因为 duke 中 遮挡 case 很少（相比 occluded duke），因此长点不明显。

也就是说现在的仓库里只能正常得到occluded的结果了？期待作者把其他的数据集的训练参数整理下！谢啦！

**Comment by wangguanan** [comment]
> > > @wangguanan
> > > 感谢解答！是的，在occluded-Duke上的结果是会高些，我发现在duck-mtmc下的结果，反而base下的结果比base+gcn+gm还要高，请问为啥呢
> > 
> > 
> > duke、market 的训练参数和 occluded-duke 不一样。
> > 另外因为 duke 中 遮挡 case 很少（相比 occluded duke），因此长点不明显。
> 
> 也就是说现在的仓库里只能正常得到occluded的结果了？期待作者把其他的数据集的训练参数整理下！谢啦！

是的，谢谢理解哈。

**Comment by wangguanan** [comment]
> 我遇到了同样的问题，请问解决了吗 @nobody-cheng

你好，请问你是在训练的时候遇到的问题，还是测试阶段。

如果是训练阶段，必须保证 bs > 1，因为 bn layer 要求 bs >1 才能计算 mean and var。

如果是测试阶段，请确认是否调用 base.set_val()，把模型设置为推理模式，这个时候 bn 会使用 running_mean and running_var, 不要求 bs >1。
如果已经调用了 base.set_val() 还报错的话，请多提供一些信息，我去看看。

抱歉最近太忙了，回复的太慢了。
