### ISSUE TITLE
how to query one image when visualize mode? I try to change batch-size but occur a error 

### ISSUE THREAD

**Issue by chgit0214** [wangguanan/HOReID#8]

**Comment by chgit0214** [comment]
bned_feature_vector_list, cls_score_list = self.bnclassifiers(feature_vector_list)
提示：ValueError: expected 2D or 3D input (got 1D input)
thanks to your answer

**Comment by wangguanan** [comment]
hi, thank you for letting me know.
I am trying to fix the bug.

**Comment by wangguanan** [comment]
please refer this issue #6 
thanks
sorry for the late response
