### ISSUE TITLE
Padding in Transformer

### ISSUE THREAD

**Issue by hh23333** [wangguanan/HOReID#9]
Hi,
Thank you for sharing code. I have a question about data preprocessing. I noticed that you use padding operation in the training phase, but without padding in the testing phase. What is the benefit of doing that. Thanks

**Comment by wangguanan** [comment]
I pad 10 and then crop to the original size. it is a kind of data augmentation to avoid deep network overfitting.

in the test stage, no pad neither crop is needed.
